version: '3.7'

########################################################################################################################
#
#   API
#
#   - change api.example.local in the label 'traefik.http.routers.api.rule' if you wish
#
#   - add an entry to your hosts file /etc/hosts:
#
#       127.0.0.1 api.example.local
#
#   - ensure your start script in package.json binds your API service to host 0.0.0.0 and port 3000
#
########################################################################################################################
services:

  api:
    build: image:${NODE_VERSION}
    working_dir: /usr/src/app
    user: "${USER_ID}:${GROUP_ID}"
    command: sh -c "yarn install && yarn start:dev"
    restart: unless-stopped
    volumes:
      - ./api:/usr/src/app
    networks:
      - net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`api.${BASE_DOMAIN}`)"
      - "traefik.http.services.api.loadbalancer.server.port=3000"

