version: '3.7'

########################################################################################################################
#
#   Angular
#
#   - change example.local in the label traefik.http.routers.client.rule if you wish
#
#   - add an entry to your hosts file /etc/hosts:
#
#       127.0.0.1 example.local
#
#   - modify the serve script in your package.json to include the arguments '--host 0.0.0.0'
#
########################################################################################################################

services:

  client:
    image: node:${NODE_VERSION}
    working_dir: /usr/src/app
    user: "${USER_ID}:${GROUP_ID}"
    command: sh -c "yarn install && yarn serve"
    restart: unless-stopped
    volumes:
      - ./client:/usr/src/app
    networks:
      - net
    stdin_open: true  # required to keep react process alive
    environment:
      HOST: 0.0.0.0
      PORT: 3000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.client.rule=Host(`${BASE_DOMAIN}`)"
      - "traefik.http.services.client.loadbalancer.server.port=3000"

