version: '3.7'

########################################################################################################################
#
#   Traefik Reverse Proxy
#
#   This snippet relies upon the example config within /traefik/traefik.yml. You must ensure when copying this to your
#   docker-compose.yml file that the path specified in the volume mount below is correct.
#
#
########################################################################################################################

networks:

  net:

services:

  traefik:
    image: traefik:v2.0
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./docker-utils/traefik/traefik.yml:/etc/traefik/traefik.yml
    networks:
      - net
    ports:
      - 80:80
      - 8080:8080
