version: '3.7'

networks:

  net:

services:

  traefik:
    image: traefik:v2.0
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ../traefik/traefik.yml:/etc/traefik/traefik.yml
    networks:
      - net
    ports:
      - 80:80
      - 8080:8080
